# coding=utf-8

DB_STRING_LENGTH = 64
DEFAULT_THREADS = 6
DEFAULT_HTTP_TIMEOUT = 15
TASK_LIMIT_DEADLINE = 7

COMMON_ROLE = "common"
SERVICE_ROLE = "service"
COMMON_FULLTIME_ROLE = "fulltime"
SPECIAL_FULLTIME_ROLE = "special"
FULLTIME_ROLE = (COMMON_FULLTIME_ROLE, SPECIAL_FULLTIME_ROLE)